config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  resources :products
  resources :keywords
  resources :categories
  resources :stores
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@stores = Store.all
  	@products = Product.all
	@categories = Category.all
	@keywords = Keyword.all  
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="container">
	<h1 style="text-align: center;">Le Admin</h1>
<nav>
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Store</a>
    <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Product</a>
    <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false">Category</a>
  </div>
</nav>

<div class="tab-content" id="nav-tabContent">
  <div class="tab-pane fade  show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
  	<table class="table  table-striped">
	  <thead>
	    <tr>
	      <th scope="col">Name</th>
	      <th scope="col">Street</th>
	      <th scope="col">Number</th>
	      <th scope="col">Zip code</th>
	      <th scope="col">City</th>
	      <th scope="col">Country</th>
	      <th cope="col"></th>
	      <th cope="col"></th>
	    </tr>
	  </thead>
	  <tbody>
	      <% @stores.each do |store| %>
	      	<tr>
		      	<td><%= store.name %></td>
		        <td><%= store.street %></td>
		        <td><%= store.number %></td>
		        <td><%= store.zip_code %></td>
		        <td><%= store.city %></td>
		        <td><%= store.country %></td>
		        <td><%= link_to 'Update', edit_store_path(store) %></td>
		        <td>
					<%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %>
				</td>
	        </tr>
	      <% end %>
	  </tbody>
	</table>
	
	<%= link_to 'Create', new_store_path %>
  </div>

  <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
  	<table class="table table-striped">
	  <thead>
	    <tr>
	      <th scope="col">Name</th>
	      <th scope="col">Color</th>
	      <th scope="col">Category</th>
	      <th scope="col">Size</th>
	      <th scope="col">Price</th>
	      <th scope="col">Store</th>
	      <th scope="col"></th>
	      <th cope="col"></th>
	    </tr>
	  </thead>

	  <tbody>
	    <% @products.each do |product| %>
	      <tr>
	        <td><%= product.name %></td>
	        <td><%= product.color %></td>
	        <td><%= product.category.name %></td>
	        <td><%= product.size %></td>
	        <td><%= product.price %></td>
	        <td><%= product.store.name %></td>
	        <td><%= link_to 'Update', edit_product_path(product) %></td>
	        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
	<%= link_to 'Create', new_product_path %>
  </div>
  
  <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
  	<table class="table  table-striped">
	  <thead>
	    <tr>
	      <th scope="col">Name</th>
	      <th scope="col"></th>
	      <th scope="col"></th>
	    </tr>
	  </thead>

	  <tbody>
	    <% @categories.each do |category| %>
	      <tr>
	        <td><%= category.name %></td>
	        <td><a href="" data-toggle="modal" data-target="#updateModal-<%= category.id %>" id="update-<%= category.id %>" class="update">
			  Update
			</a></td>
			<td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>


<div class="modal fade" id="updateModal-<%= category.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Edit Category</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form  action="/categories/<%= category.id %>"  accept-charset="UTF-8" class="edit_category" id="edit_category" method="post">
		<input type="hidden" name="_method" value="patch">
		<div class="modal-body">
			<div class="form-group">
				<label for="category[name]" >Name</label>
				<input type="text" class="form-control" id="category[name]" name="category[name]" aria-describedby="category[name]" value="<%= category.name %>">
			</div>
			<div class="form-group" id="keyword-edit">
				<h5>Keywords</h5>
				<% x = @keywords.select { |keyword| keyword.category_id == category.id } %>
				<% data = [] %>
				<% x.each do |key| %>
					<% data.push(key.name) %>
				<% end %>
				 <input type="hidden" class="form-control" id='category[keywords].edit-<%= category.id %>'  name="category[keywords]" aria-describedby="category[keywords]" value="<%= data.join(",")%>">
				<input type="text" id="addKeywordEdit"  id-target="<%= category.id %>" class="form-control myInputEdit" placeholder="Write the keyword and press enter">
				<br>
				<div id="keyword-body-edit-<%= category.id %>">
					<% @keywords.each do |keyword| %>
						<% if keyword.category_id == category.id%>
						<div class="container">
							<div class="row">
								<div class="col-sm">
									<%= keyword.name %>
								</div>
								<div class="col-sm">
									<a href="javascript:void(0);"  id-target="<%= keyword.category_id %>" onclick="deleteKeywordEdit(this)">Delete</a>
								</div>
							</div>
						</div>
						<% end %>
					<% end %>
				</div>
			</div>
		</div>
		<div class="modal-footer">
			<button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
			<button type="submit"   name="commit"  class="btn btn-primary">Submit</button>
		</div>
      </form>
    </div>
  </div>
</div>

	      </tr>
	    <% end %>
	  </tbody>
	</table>

	<br>

<!-- Button trigger modal -->
<a href="" data-toggle="modal" data-target="#createModal">
  Create
</a>


<!-- Modal Create Category -->
<div class="modal fade" id="createModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New Category</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form  action="/categories"  accept-charset="UTF-8" class="new_store" id="new_store" method="post">
      <div class="modal-body">
		<div class="form-group">
			<label for="category[name]" >Name</label>
			<input type="text"  id="category[name]" name="category[name]" aria-describedby="category[name]" class="form-control">
		</div>
		<div class="form-group">
			 <h5>Keywords</h5>
			 <input type="hidden" class="form-control" id='category[keywords].create'  name="category[keywords]" aria-describedby="category[keywords]">
			<button id="addKeyword" style="background:transparent; border: 0;" ></button>
			<input type="text" class="form-control" id='myInput' placeholder="Write the keyword and press enter">
			<br>
			<div id="keyword-body">
			 </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        <button type="submit"   name="commit"  class="btn btn-primary">Submit</button>
      </div>
      </form>
    </div>
  </div>
</div>

  </div>
</div>
</div>


<script>
	var buttonKeyword = document.getElementById("addKeyword");
	var buttonKeywordEdit = document.getElementById("addKeywordEdit");
	var inputKeyword = document.getElementById("myInput");

	function deleteKeyword (element) {
		element.parentElement.parentElement.parentElement.remove();
		var table = document.getElementById("keyword-body");
		var keys = getKeywords(table);
		var keywords = document.getElementById("category[keywords].create");
		keywords.value = keys
	}

	function deleteKeywordEdit (element) {
		var inputKeyword = element;
		var id = inputKeyword.getAttribute('id-target')
		var table = document.getElementById("keyword-body-edit-" + id);
		element.parentElement.parentElement.parentElement.remove();
		var keys = getKeywords(table);
		var keywords = document.getElementById("category[keywords].edit-" + id);
		keywords.value = keys
	}

	function generateTemplate (data) {
		return `<div class="row">
						<div class="col-sm">
							${data}
						</div>
						<div class="col-sm">
							<a href="javascript:void(0);" onclick="deleteKeyword(this)">Delete</a>
						</div>
					</div>`
	}

	function generateTemplateEdit (data) {
		return `<div class="row">
				<div class="col-sm">
					${data}
				</div>
				<div class="col-sm">
					<a href="javascript:void(0);" onclick="deleteKeywordEdit(this)">Delete</a>
				</div>
			</div>`
	}

	$('.myInputEdit').keydown(function (e) {
		if (e.keyCode == 13) {
			e.preventDefault();
			var inputKeyword = e.target;
			var id = inputKeyword.getAttribute('id-target')
			var value = inputKeyword.value;
			inputKeyword.value = "";
			var table = document.getElementById("keyword-body-edit-" + id);
			var nodeDIV = document.createElement("DIV");
			nodeDIV.classList.add("container");
			var template = generateTemplateEdit(value);
			nodeDIV.innerHTML = template
			table.appendChild(nodeDIV);
			var keywords = document.getElementById("category[keywords].edit-" + id);
			var keys = getKeywords(table);
			keywords.value = keys
        	return false;
		}
	})

	$('myInput').keydown(function (e) {
		if (e.keyCode == 13) {
			e.preventDefault();
        	return false;
		}
	})
	
	function getKeywords (table) {
		var keywordsSend = []
		var arr = Array.prototype.slice.call( table.children );
		arr.forEach(element => {
			var keywordWrite = element.children[0].children[0].innerHTML;
			keywordsSend.push(keywordWrite.trim());
		});
		keywordsSend = keywordsSend.join(",")
		return keywordsSend
	}

	window.addEventListener('load', function () {
		var table = document.getElementById("keyword-body");
		keywords = getKeywords(table)
	})

	// buttonKeywordEdit.addEventListener("click",function(e) {
	// 	e.preventDefault();
	// 	console.log('asd')
	// })

	buttonKeyword.addEventListener("click",function(e) {
		e.preventDefault();
		var value = inputKeyword.value;
		inputKeyword.value = "";
		var table = document.getElementById("keyword-body");
		var nodeDIV = document.createElement("DIV");
		nodeDIV.classList.add("container");
		var template = generateTemplate(value);
		nodeDIV.innerHTML = template
		table.appendChild(nodeDIV);
		var keywords = document.getElementById("category[keywords].create");
		var keys = getKeywords(table);
		keywords.value = keys
	});
</script>